feat: custom home tab
hakadao/BewlyBewly pull request #314
Opened 2024-02-20 05:39 UTC by cloudflypeng

2024-02-20 07:11 UTC, hakadao commented
Thxs. However, remember to point out what language you cannot translate in your PR, this will help us to maintain the untranslated language. 
https://github.com/hakadao/BewlyBewly?tab=readme-ov-file#i18n

And it's possible that the default tab configuration may not be incorporated into the settings
https://github.com/hakadao/BewlyBewly/issues/269#issuecomment-1953594171

2024-02-20 07:55 UTC, cloudflypeng commented
> default tab configuration

the default tab configuration has been deleted

2024-02-20 08:00 UTC, hakadao commented
十分感謝，今晚我會詳細看看，不過記得在pr description裏面說一下你有哪些語言沒有翻譯，方便日後維護

2024-02-20 17:01 UTC, hakadao commented
這裡學dock一樣加上reset和描述文字先吧
<img width="780" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/f1b3a9fc-0ae0-4072-ad4a-d1993db3c286">

2024-02-20 17:19 UTC, hakadao requested changes

2024-02-20 17:19 UTC, hakadao commented on src/_locales/cmn-CN.yml
> +  group_home_tab: 首页tab栏配置
直接叫首頁tab

2024-02-20 17:19 UTC, hakadao commented on src/_locales/cmn-CN.yml
> +  group_home_tab: 首页tab栏配置
直接叫 `首页标签栏` 吧還是
group_home_tabs: 首页标签栏

2024-02-20 17:19 UTC, hakadao commented on src/_locales/cmn-CN.yml
> +  home_tab_order: Tab展示顺序
改成 home_tabs_adjustment:  标签栏调整

2024-02-20 17:19 UTC, hakadao commented on src/_locales/cmn-CN.yml
> +  home_tab_order_desc: 第一个激活的 Tab 项是默认界面
home_tabs_adjustment_desc: 第一个激活的 Tab 项是默认界面

2024-02-20 17:19 UTC, hakadao commented on src/_locales/en.yml
> +  group_home_tab: Tab config
group_home_tabs: Home Tabs

2024-02-20 17:19 UTC, hakadao commented on src/_locales/en.yml
> +  home_tab_order_desc: The first activated tab is the default page
home_tabs_adjustment: Tabs adjustment
home_tabs_adjustment_desc: The first activated tab is the default page

2024-02-21 02:07 UTC, cloudflypeng commented
i fix it , but there is one thing i dont no how to do in this project
the i18n use t() but it just can use in setup or the template
so i copy the tabs list 

```typescript
const homeTabs = computed((): HomeTab[] => {
  return [
    {
      label: t('home.for_you'),
      value: HomeSubPage.ForYou,
    },
    {
      label: t('home.following'),
      value: HomeSubPage.Following,
    },
    {
      label: t('home.subscribed_series'),
      value: HomeSubPage.SubscribedSeries,
    },
    {
      label: t('home.trending'),
      value: HomeSubPage.Trending,
    },
    {
      label: t('home.ranking'),
      value: HomeSubPage.Ranking,
    },
  ]
})
```

and now this list is in two file, how can i writer to defined it in one place

2024-02-21 02:50 UTC, hakadao commented
> i fix it , but there is one thing i dont no how to do in this project
> the i18n use t() but it just can use in setup or the template
> so i copy the tabs list

u can just store the i18n key like this 
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/32d2d1d1-f698-4055-860f-e628f1188a44)
when you wanna use it
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/57862d46-08a4-4841-9189-3711bc063f16)

btw im not sure if i should put it into a new Consts.ts file to store all these constants, or maybe put it into the ~/store/ (?)🤔

anyway, thank u for providing the new method to compare the stored object list and the default object list

2024-02-25 11:16 UTC, merged